### ISSUE TITLE
AvP's used version of ForgeGradle receiving 400 responses during build

### ISSUE THREAD

**Issue by bvanseg** [Ri5ux/AliensVsPredator#106]
While building the project locally for AvP using the command `./gradlew setupDecompWorkspace --refresh-dependencies`, the following exception occurs:
```
Error downloading asset (try 4) : realms/lang/yo_ng.lang
java.io.IOException: Server returned HTTP response code: 400 for URL: http://resources.download.minecraft.net/71/71c86a1d2324e5337c2326518a26937294491352
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1902)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1500)
        at java.net.URL.openStream(URL.java:1093)
        at net.minecraftforge.gradle.tasks.DownloadAssetsTask$GetAssetTask.call(DownloadAssetsTask.java:189)
        at net.minecraftforge.gradle.tasks.DownloadAssetsTask$GetAssetTask.call(DownloadAssetsTask.java:150)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
```
This exception is additionally thrown for every single asset in the game (textures, sounds, lang files, etc.) during build. This is because the version of ForgeGradle that AvP is using hits minecraft's asset cdn using http and not https. The culprit line is here: https://github.com/MinecraftForge/ForgeGradle/blob/FG_2.3/src/main/java/net/minecraftforge/gradle/common/Constants.java#L119

The ForgeGradle developers have expressed that they will no longer be supporting older versions of the plugin. That leaves two options:
- Fork the repo's 2.3 version, change the URL to use https, publish the forked change and have AvP reference that fork.
- Port AvP to MC 1.13 and use a newer version of the ForgeGradle plugin.

**Comment by bvanseg** [comment]
Resolved by #59. Closing.
