### ISSUE TITLE
EntityLookHelper crash with Queens

### ISSUE THREAD

**Issue by darthvader45** [Ri5ux/AliensVsPredator#20]
Okay, separate crash dealing with the Queen and its methods that refer to EntityLookHelper.  This crash is gonna pursue me forever unless it's dealt with.

@Ri5ux 

```
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 11/6/16 12:14 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.entity.ai.EntityLookHelper.func_75651_a(SourceFile:18)
	at net.minecraft.entity.ai.EntityAIAttackOnCollide.func_75246_d(EntityAIAttackOnCollide.java:93)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:103)
	at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:640)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1774)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:452)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:25)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:272)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:30)
	at org.avp.entities.mob.EntitySpeciesAlien.func_70071_h_(EntitySpeciesAlien.java:172)
	at org.avp.entities.mob.EntityXenomorph.func_70071_h_(EntityXenomorph.java:78)
	at org.avp.entities.mob.EntityQueen.func_70071_h_(EntityQueen.java:249)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at WorldServerOF.func_72870_g(WorldServerOF.java:347)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by darthvader45** [comment]
It seems to be the server that's crashing, forcing a client crash since it's the integrated server.  This is extremely annoying.
