### ISSUE TITLE
NPE on save 

### ISSUE THREAD

**Issue by ProsperCraft** [Ri5ux/AliensVsPredator#24]
Stacktrace in console - 

[12:04:20] [Server thread/INFO] [MDX]: Saved 0 hives for level 'world-drtardis'/DimensionAbyss
[12:04:20] [Server thread/INFO] [MDX]: Saved 0 hives for level 'world-drtardis'/Tardis Interior
[12:04:20] [Server thread/INFO] [MDX]: Saved 0 hives for level 'world-drtardis'/Trenzalore
[12:04:20] [Server thread/INFO] [MDX]: Saved 0 hives for level 'world-drtardis'/Tardis Interior
[12:04:20] [Server thread/INFO] [MDX]: Saved 0 hives for level 'world-drtardis'/Utumno
[12:04:20] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[12:04:20] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at org.avp.util.XenomorphHive.save(XenomorphHive.java:209)
[12:04:20] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at org.avp.event.HiveHandler.saveData(HiveHandler.java:149)
[12:04:20] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at org.avp.SaveHandler.onWorldSave(SaveHandler.java:59)
[12:04:20] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at cpw.mods.fml.common.eventhandler.ASMEventHandler_324_SaveHandler_onWorldSave_Save.invoke(.dynamic)
[12:04:20] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[12:04:20] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
[12:04:20] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:810)
[12:04:20] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318)
[12:04:20] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:569)
[12:04:20] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at fastcraft.at.a(F:978)
[12:04:20] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at fastcraft.H.aq(F:36)
[12:04:20] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
[12:04:20] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[12:04:20] [Server thread/INFO] [MDX]: Saved 0 hives for level 'world-drtardis'/Skaro
[12:04:20] [Server thread/INFO] [MDX]: Saved 0 hives for level 'world-drtardis'/Dungeons
[12:04:20] [Server thread/INFO] [MDX]: Saved 0 hives for level 'world-drtardis'/Cave Game
[12:04:20] [Server thread/INFO] [MDX]: Saved 0 hives for level 'world-drtardis'/Aether
[12:04:20] [Server thread/INFO] [MDX]: Saved 0 hives for level 'world-drtardis'/Minecraft Infdev
[12:04:20] [Server thread/INFO] [MDX]: Saved 0 hives for level 'world-drtardis'/Tardis

**Comment by darthvader45** [comment]
Yeah, saw this too.

**Comment by Ri5ux** [comment]
This is now resolved (6d4cc9acc0278d1865f7ea146053f1f31fbdb970)
